### PR TITLE
upload illustrator & png files

### PR DESCRIPTION
**Pull request by silvernberry**
New Logo for Auguth Research Foundation. The Logo is inspired from Greek letter - Small Lambda. Also the Font Face for the banner is Sans Serif, a perfect font for a research based organization. The Color is a Shade of Cyan (Green & Blue Mix), suitable for a tech company, other colors are tried and finalized this as a more suitable choice.

### CODE REVIEW

**Review by jobyreuben — APPROVED** [review]
Looks Good, thanks 👌

**Review by I-Corinthian — CHANGES_REQUESTED** [review]
looks good, Can we try with a triangle in the center of "A"

**Comment by Purva-Chaudhari** [comment]
LGTM!

**Review by Purva-Chaudhari — APPROVED** [review]

**Comment by ultratyphoon01** [comment]
The colour could be bit darker I guess?

**Comment by silvernberry** [comment]
> The colour could be bit darker I guess?

How about this, @ultratyphoon01 

Screenshot 2024-02-08 at 12 29 38 AM

**Comment by silvernberry** [comment]
> looks good, Can we try with a triangle in the center of "A"

Here is the couple of versions like you asked @I-Corinthian 

Screenshot 2024-02-08 at 12 25 58 AM
Screenshot 2024-02-08 at 12 26 07 AM

or the old one is relatively better ?

Screenshot 2024-02-08 at 12 26 37 AM

**Comment by jobyreuben** [comment]
> > The colour could be bit darker I guess?
> 
> How about this, @ultratyphoon01
> 
> Screenshot 2024-02-08 at 12 29 38 AM

Color Looks Good for me

**Comment by ultratyphoon01** [comment]
@silvernberry  @jobyreuben 
Yes the new darkened version looks perfect

**Review by ultratyphoon01 — APPROVED** [review]

**Comment by jobyreuben** [comment]
@silvernberry Can you update the approved logo by @Purva-Chaudhari @jobyreuben @ultratyphoon01 So we can merge this PR requiring 4 majority reviews to merge.

**Pull request merged**
